name: Deploy app
run-name: Deploy DF # shows env in the run title

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]++[0-9]*'
    branches-ignore:
      - 'main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:    
  deploy-backend:
    name: Deploy Backend – DF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pick env
        run: |
          echo "hello DF"